name: risczero toolchain install
description: Install risczero toolchain

inputs:
  risczero-version:
    description: 'Version of the RISC Zero zkvm to install'
    required: false
    default: '2.3.0'
    type: string

  toolchain-version:
    description: 'Version of the RISC Zero toolchains to install'
    required: false
    default: '1.88.0'
    type: string

  cpp-version:
    description: 'Version of the RISC Zero cpp toolchain to install'
    required: false
    default: '2024.1.5'
    type: string

  groth16-version:
    description: 'Version of the risc0-groth16 component to install'
    required: false
    default: '0.1.0'
    type: string

  install-groth16:
    description: 'Whether to install the risc0-groth16 component; required for Groth16 GPU proving'
    required: false
    default: boolean
    type: bool

runs:
  using: composite
  steps:
    - name: install rust
      uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
      with:
        toolchain: ${{ inputs.toolchain-version }}

    - name: cache risc0 toolchain
      id: risc0-cache
      uses: actions/cache@v4
      with:
        path: ~/.risc0
        key: risc0-${{ runner.os }}-${{ runner.arch }}-${{ inputs.risczero-version }}-${{ inputs.toolchain-version }}-${{ inputs.cpp-version }}${{ inputs.install-groth16 == 'true' && format('-groth16-{0}', inputs.groth16-version) || '' }}

    - name: install rzup
      if: steps.risc0-cache.outputs.cache-hit != 'true'
      run: |
        curl -L https://risczero.com/install | bash
        echo "$HOME/.risc0/bin" >> $GITHUB_PATH
      shell: bash

    - name: install rzup components
      if: steps.risc0-cache.outputs.cache-hit != 'true'
      run: |
        rzup install --verbose cargo-risczero ${{ inputs.risczero-version }}
        rzup install --verbose r0vm ${{ inputs.risczero-version }}
        rzup install --verbose rust ${{ inputs.toolchain-version }}
        rzup install --verbose cpp ${{ inputs.cpp-version }}
      shell: bash

    - name: install risc0-groth16
      if: inputs.install-groth16 == 'true' && steps.risc0-cache.outputs.cache-hit != 'true'
      run: rzup install --verbose risc0-groth16 ${{ inputs.groth16-version }}
      shell: bash

    - name: add rzup to PATH
      run: echo "$HOME/.risc0/bin" >> $GITHUB_PATH
      shell: bash

    - name: test r0vm
      shell: bash
      run: r0vm --version

    - name: test risczero
      shell: bash
      run: cargo risczero --version
