name: risczero toolchain install
description: Install risczero toolchain

inputs:
  risczero-version:
    description: 'Version of the RISC Zero zkvm to install'
    required: false
    default: '2.3.0'
    type: string

  toolchain-version:
    description: 'Version of the RISC Zero toolchains to install'
    required: false
    default: '1.88.0'
    type: string

  install-groth16:
    description: 'Whether to install the risc0-groth16 component; required for Groth16 GPU proving'
    required: false
    default: boolean
    type: bool

runs:
  using: composite
  steps:
    - name: install rust
      uses: risc0/risc0/.github/actions/rustup@v3.0.3
      with:
        toolchain: ${{ inputs.toolchain-version }}

    - name: install rzup
      run: |
        curl -L https://risczero.com/install | bash
        echo "$HOME/.risc0/bin" >> $GITHUB_PATH
      shell: bash

    - name: install rzup components
      run: |
        rzup install --verbose --force cargo-risczero ${{ inputs.risczero-version }}
        rzup install --verbose --force r0vm ${{ inputs.risczero-version }}
        rzup install --verbose --force rust ${{ inputs.toolchain-version }}
        rzup install --verbose --force cpp
      shell: bash

    - name: install risc0-groth16
      if: ${{ inputs.install-groth16 }}
      run: rzup install --verbose --force risc0-groth16
      shell: bash

    - name: test r0vm
      shell: bash
      run: r0vm --version

    - name: test risczero
      shell: bash
      run: cargo risczero --version
