config:
  aws:region: us-west-2
  base-prover:BASE_STACK: organization/bootstrap/services-staging
  base-prover:BOUNDLESS_MARKET_ADDR: 0x7abb16522f4599481361d318b765af988bfcca8e
  base-prover:CHAIN_ID: "84532"
  base-prover:DOCKER_DIR: ../../
  base-prover:DOCKER_TAG: latest
  base-prover:GH_TOKEN_SECRET:
    secure: v1:g+sVxP7+QecQyHzA:zRtgTHdIW9hcj3ihad8AwdSvPnF8jN7CWnQj/ExrhsZsPZnh0n6K+5KfsRxcHyMK/ysOyfVDUeFmMUL3vbNmfcX+4IlctznGKLXDgdY/+WaH6Pt1EGp7xTqR1usiWQ8z7cKS6Fo0DWms6tLUUA==
  base-prover:ORDER_STREAM_URL:
    secure: v1:rR9eC9Ek5GQAfLd+:rPoNXX63D+U9NcxWhI865zwwoam07s+OMaxx8pJG/kFRCfgZbAEQwZJeb2sBJdPEVJ1Oud2zZzbbbtkI+YvIxEAXHuFIKF2eUe6RQDcCVszjEQQKf9f67eo8zq8=
  base-prover:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  base-prover:SET_VERIFIER_ADDR: 0x1Ab08498CfF17b9723ED67143A050c8E8c2e3104
  base-prover:COLLATERAL_TOKEN_ADDRESS: 0xCBA5Fd30105984125395c18B6E6b1bf603408629
  base-prover:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-staging-launch
  bento-prover:BROKER_TOML_PATH: tomls/bento/broker-staging-84532.toml
  bento-prover:LOG_JSON: "true"
  bento-prover:SEGMENT_SIZE: "19"
  bento-prover:SNARK_TIMEOUT: "240"
  base-prover:ETH_RPC_URL:
    secure: v1:50aHb1nN5P+xF3y9:ApyIvi1thPXTbINCtSeeeJbKnlEMNcthhN62NIThgGihljYmUizalpceGl/UBKKi/pcTpTw6Kb//5YwpIDc45w8t6/Yu5y0ngG5P
  bento-prover:PRIVATE_KEY_1:
    secure: v1:neNgD6o1PDMuAaoB:R0QfJOYSskn5wlqJmzS1qu5VWueIZYehKMajqy6fuEB/FPB/7D1uli5IJjvXaXlrG6TnxlOfmW3LXwoAIhFq97/VqgcqGQHl/ZBezU4+6CU=
  bento-prover:PRIVATE_KEY_2:
    secure: v1:Lwzj5EI1qL2EP0nQ:cUAITs5lYcw0LbyWUlXsPmphAvMNO1941ykhgNUK3jv28oR4ffCy+43V7NonWuHnSb+mDqyytJvTss/S+dM93LnxXcu2cQ6TOQbCLl7aCms=
  bento-prover:BRANCH: main
  bento-prover:POVW_LOG_ID_1:
    secure: v1:1lQVN+nVLrmkGB1R:DZXfJFHh38pitoWWQKfgIZxm5WauDuITCjxA/dI/ScdsjGWcTkXN/4w/O2CcnrjMrzNKrfZpWNCdGQ==
  bento-prover:POVW_LOG_ID_2:
    secure: v1:3vgyaIHUMVAaEGMD:PnpU0bBVMZv8kP8qHurcJmpIyM/XIZ5hzOoYpubUPA+XezzpTIz225ckzQUSu5ecg2kNmKd0I0TGzQ==
secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAGDMFzAwM24x2rddho4Hvk0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbUDWfFjkYqahQOgdAgEQgDtODkDHrLQ9qL2Vf/Lel/IE9IunMXhWayYkSWsuYcYqCd0YyY2+bjlBBewirws1+qk+KKJAa3+k79ZWhA==
