name: risczero toolchain install
description: Install risczero toolchain

runs:
  using: composite
  steps:
    - name: install rust
      uses: risc0/risc0/.github/actions/rustup@release-2.0
      with:
        toolchain: '1.85'

    - name: Install rzup
      env:
        ENV_PATH: test
      shell: bash
      run: |
        curl -L https://risczero.com/install | bash
        echo "$HOME/.risc0/bin" >> $GITHUB_PATH

    - name: rzup install
      shell: bash
      run: rzup install rust 1.85.0

    - name: rzup install cpp
      shell: bash
      run: rzup install cpp
