secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHjo9dP83MIkRU7zP48vJb5veObMz9xpFGm6gYEXRHbpqwGnPMfb0/YC290qpYVoArOyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1q5NuKHP11fJnr5JAgEQgDssGchsH3jIMq0dxuVQobD8cMOCRNPWSPIpXgnWHECgxq+BGYuHZ4xVTuWKtXRa9t0Xd0M2SbmiMnxtSw==
config:
  aws:region: us-west-2
  kailua-batch:BASE_STACK: organization/bootstrap/services-staging
  kailua-batch:CHAIN_ID: "10"
  kailua-batch:KAILUA_IMAGE: ghcr.io/boundless-xyz/kailua:c003948
  kailua-batch:TASK_CPU: "8"
  kailua-batch:TASK_MEMORY_MIB: "8192"
  kailua-batch:LOG_RETENTION_DAYS: "30"
  # Set true if private subnets have no NAT and you need outbound internet for the task
  kailua-batch:ASSIGN_PUBLIC_IP: "false"
  kailua-batch:SCHEDULE_COUNT: "1"
  kailua-batch:SCHEDULE_WINDOW_MINUTES: "20"
  kailua-batch:TASKS_PER_MINUTE: "2"
  kailua-batch:MAX_RUNNING_TASKS: "4"
  kailua-batch:SKIP_AWAIT_PROOF: "true"
  kailua-batch:KAILUA_WORKDIR: /kailua
  kailua-batch:MODE: debug
  kailua-batch:DATA_REL: .localtestdata/op-mainnet
  kailua-batch:S3_BUCKET: zkasper-staging
  kailua-batch:R2_DOMAIN: https://staging-signal-artifacts.beboundless.xyz
  kailua-batch:AWS_REGION: auto
  kailua-batch:LOG_VERBOSITY: -vvv
  kailua-batch:BOUNDLESS_MARKET_ADDRESS: "0x7abb16522f4599481361d318b765af988bfcca8e"
  kailua-batch:BOUNDLESS_SET_VERIFIER_ADDRESS: "0x1Ab08498CfF17b9723ED67143A050c8E8c2e3104"
  kailua-batch:BOUNDLESS_COLLATERAL_TOKEN_ADDRESS: "0xCBA5Fd30105984125395c18B6E6b1bf603408629"
  kailua-batch:BOUNDLESS_DYNAMIC_PRICING_TIMEOUT_MODIFIER: "2"
  kailua-batch:BOUNDLESS_DYNAMIC_PRICING_RAMP_UP_MODIFIER: "2"
  kailua-batch:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-staging
  kailua-batch:ENABLE_PAGERDUTY_ALERTS: "true"
  kailua-batch:L1_RPC:
    secure: v1:rjVQr/QZVHx1AwfZ:CVgycgRPhePeD9lv9wJXan7+nyqq/bLGGWLnJqBlV8fPlUjJtOBKpmYCd9tsqIP319hmav75YofVdAR36F+OpvEWVeU/ROdaQfay694qlbMIf4yQwiaF7Jz/jX9AVL5ssPABAzyya8+57gzaZN4lJmerhw==
  kailua-batch:L2_RPC:
    secure: v1:X+ZK/BB765UbCja5:IXVzfkVDgWd7A9DPVE44tEtPtoV8HzC5zHDpgPxxk06sTY5KLgORS4iJQuiIke93g/b0GvJwJ3bJniDngB3kZzRFPkFhdFbY8UEpI6teM/ZbP0wVExe796LM31+Qx/uau60FypJLIgvsCvtmO5Vu
  kailua-batch:OP_NODE:
    secure: v1:H4oYkRCZcTwhD21t:uRDyD01ck5/TreXRS8RAXI++Qboaxwz96msA96Sz9zH1Mj5LtVZMZ/3gbLYq4HjELQih7B9vtgURPbSad3b4nvKygDyUkRC25ap+qvFu8pT/tmWFr35rPJmSiq9MLctZyjB8PvRZOwWizyWUF3pF
  kailua-batch:S3_UPLOAD_ACCESS_KEY:
    secure: v1:uFycwmlIKUO7NsKE:dRU7bvvPSrwczbfLSTROn4cecsWm4efCNKE6myOw1NkCF/p9qWGib0cNoMj9PdZE
  kailua-batch:S3_SECRET_ACCESS_KEY:
    secure: v1:itWPjPSbiWUcm4Yh:LIdK/8840n9YHylUxXmxmp+arYj09UliAIPlWt/e4wLm8ULIuPIigvVY64j79tDkqpnOrpvznEsmEEoxu1feoThvnSV45QcgonVEpLVvlJw=
  kailua-batch:WALLET_KEY:
    secure: v1:lRAWZbowXgQkSqSX:Ut0Qvfyo1slJtxMZPc/WpvuLQlC2+bsPmPKhf5bOlGQP1u2bAv+o8DJEkfzEnozOHqMgma/5HtEqYJKtvTawf5p0VjFuv9DX3ByhwDJZeaI=
  kailua-batch:BOUNDLESS_RPC_URL:
    secure: v1:6Twx1ICtEXpBAuP9:5zjb9S1hfA8ZQCyMnBzfHsODQttEpPUyJ/lMquS6Dm1JPluU+JThVi/8aw2Ai7awi3Gd5YNn7TcmIi3ARIY5smNupuAMjXSCCYlyn3acMt1lxOmOyXOrBdu9XAO7CvmGQKWXXgTDlcJeUsZ5dqMd+w==
  kailua-batch:L1_BEACON:
    secure: v1:grfhSE8cTVS2QJSO:Wn0BYKm1hrQ0V6jyWRIzaATjgXRUAx3xNwKaWyRC83BgIFrgR+LeWborhxOlzJTruxXFUxvSCnoGbIAI08LJyRkBlPRFQxQMry3qk0jzzleLK1xHcfYnroIaScfKk4fnsKDm1dTe1xwnhJvepjxPEWWMFw==
  kailua-batch:S3_URL:
    secure: v1:uic0XwOCVP8ecxaT:GwwYi64Gisrq7VKu+mTpqxYhdCWOpOkBGS+oEMvPGEA1qMcpiwalNOfS8WmgzCIdG0+l0h3+1xMZ/RqyPEWO43klUPk4+GbI4rjY0Xeen1bk
  kailua-batch:BOUNDLESS_ORDER_STREAM_URL:
    secure: v1:MPne/quadp5SpIJV:UTCRs341PjeijpWIBNIxIassKAYSZd+I9SOejCns4aDI3+4dgBHH1qCl6Iem9sH9GOVsSMNhh/XXfpgxgh1D0Ct3gPuLvTiZa2fSuUmMXDRnh+vRm2u3PrhbhO0=
