name: image-builder
description: Builds Docker images for Boundless services and pushes to ECR
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
