[market]
mcycle_price = "0.001"
assumption_price = "0.1"
peak_prove_khz = 500
parallel_proofs = 1
min_deadline = 150
lookback_blocks = 100
max_stake = "0.5"
skip_preflight_ids = []
max_file_size = 50_000_000

[prover]
status_poll_ms = 1000
bonsai_r0_zkvm_ver = "1.1.1"
req_retry_count = 3
#agg_set_guest_path = "./target/riscv-guest/riscv32im-risc0-zkvm-elf/release/aggregation-set-guest"
#assessor_set_guest_path = "./target/riscv-guest/riscv32im-risc0-zkvm-elf/release/assessor-guest"

[batcher]
batch_max_time = 1000
batch_size = 1
block_deadline_buffer_secs = 120
