[profile.default]
src = "contracts/src"
out = "contracts/out"
fs_permissions = [{ access = "read", path = "contracts/out" }, { access = "read", path = "contracts/deployment.toml" }]
libs = ["lib"]
script = "contracts/scripts"
test = "contracts/test"
ffi = true
evm_version = 'cancun'
via_ir = true
optimizer = true
# Use 10k runs because it doesn't seem to slow down compilation, and does shave off a bit of gas.
optimizer_runs = 10000
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["BoundlessMarket"]
solc_version = "0.8.26"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"

[profile.reference-contract]
src = "contracts/src"
out = "contracts/reference-contract/out"
test = "contracts/reference-contract/test"
libs = ["lib"]
ffi = true
build_info = true
extra_output = ["storageLayout"]
