[workspace]
resolver = "2"
members = ["apps"]
exclude = ["lib"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
# Intra-workspace dependencies
guest-assessor = { path = "../../crates/guest/assessor" }
guest-util = { path = "../../crates/guest/util" }
boundless-market = { path = "../../crates/boundless-market" }
boundless-market-client = { path = "../../crates/boundless-market-client" }
broker = { path = "../../crates/broker" }

# risc0 monorepo dependencies.
risc0-build = { version = "1.2", features = ["docker"] }
risc0-zkvm = { version = "1.2", default-features = false }

# risc0-ethereum dependencies.
guest-set-builder = { git = "https://github.com/risc0/risc0-ethereum", tag = "aggregation-v0.2.1" }
risc0-aggregation =  { version = "0.2" }
risc0-build-ethereum = { version = "1.3" }
risc0-ethereum-contracts = { version = "1.3" }

alloy = { version = "0.6" }
alloy-primitives = { version = "0.8", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.8" }
anyhow = { version = "1.0" }
bincode = { version = "1.3" }
bytemuck = { version = "1.16" }
clap = { version = "4.5", features = ["derive", "env"] }
dotenvy = "0.15"
futures-util = "0.3"
hex = { version = "0.4" }
log = { version = "0.4" }
erc20-counter-methods = { path = "./methods" }
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"
sha2 = { version = "0.10" }
test-log = { version = "0.2", features = ["trace"] }
tokio = { version = "1" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
