CREATE TABLE IF NOT EXISTS hourly_market_summary (
  period_timestamp                        BIGINT PRIMARY KEY,
  total_fulfilled                         BIGINT NOT NULL,
  unique_provers_locking_requests         BIGINT NOT NULL,
  unique_requesters_submitting_requests   BIGINT NOT NULL,
  total_fees_locked                       TEXT NOT NULL,
  total_collateral_locked                 TEXT NOT NULL,
  total_locked_and_expired_collateral     TEXT NOT NULL,
  p10_lock_price_per_cycle                TEXT NOT NULL,
  p25_lock_price_per_cycle                TEXT NOT NULL,
  p50_lock_price_per_cycle                TEXT NOT NULL,
  p75_lock_price_per_cycle                TEXT NOT NULL,
  p90_lock_price_per_cycle                TEXT NOT NULL,
  p95_lock_price_per_cycle                TEXT NOT NULL,
  p99_lock_price_per_cycle                TEXT NOT NULL,
  total_requests_submitted                BIGINT NOT NULL,
  total_requests_submitted_onchain        BIGINT NOT NULL,
  total_requests_submitted_offchain       BIGINT NOT NULL,
  total_requests_locked                   BIGINT NOT NULL,
  total_requests_slashed                  BIGINT NOT NULL,
  total_expired                           BIGINT NOT NULL DEFAULT 0,
  total_locked_and_expired                BIGINT NOT NULL DEFAULT 0,
  total_locked_and_fulfilled              BIGINT NOT NULL DEFAULT 0,
  locked_orders_fulfillment_rate          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  total_program_cycles                    TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  total_cycles                            TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  best_peak_prove_mhz                     BIGINT NOT NULL DEFAULT 0,
  best_peak_prove_mhz_prover              TEXT,
  best_peak_prove_mhz_request_id          TEXT,
  best_effective_prove_mhz                BIGINT NOT NULL DEFAULT 0,
  best_effective_prove_mhz_prover         TEXT,
  best_effective_prove_mhz_request_id     TEXT,
  updated_at                              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_hourly_market_period_timestamp ON hourly_market_summary(period_timestamp DESC);

CREATE TABLE IF NOT EXISTS daily_market_summary (
  period_timestamp                        BIGINT PRIMARY KEY,
  total_fulfilled                         BIGINT NOT NULL,
  unique_provers_locking_requests         BIGINT NOT NULL,
  unique_requesters_submitting_requests   BIGINT NOT NULL,
  total_fees_locked                       TEXT NOT NULL,
  total_collateral_locked                 TEXT NOT NULL,
  total_locked_and_expired_collateral     TEXT NOT NULL,
  p10_lock_price_per_cycle                TEXT NOT NULL,
  p25_lock_price_per_cycle                TEXT NOT NULL,
  p50_lock_price_per_cycle                TEXT NOT NULL,
  p75_lock_price_per_cycle                TEXT NOT NULL,
  p90_lock_price_per_cycle                TEXT NOT NULL,
  p95_lock_price_per_cycle                TEXT NOT NULL,
  p99_lock_price_per_cycle                TEXT NOT NULL,
  total_requests_submitted                BIGINT NOT NULL,
  total_requests_submitted_onchain        BIGINT NOT NULL,
  total_requests_submitted_offchain       BIGINT NOT NULL,
  total_requests_locked                   BIGINT NOT NULL,
  total_requests_slashed                  BIGINT NOT NULL,
  total_expired                           BIGINT NOT NULL DEFAULT 0,
  total_locked_and_expired                BIGINT NOT NULL DEFAULT 0,
  total_locked_and_fulfilled              BIGINT NOT NULL DEFAULT 0,
  locked_orders_fulfillment_rate          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  total_program_cycles                    TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  total_cycles                            TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  best_peak_prove_mhz                     BIGINT NOT NULL DEFAULT 0,
  best_peak_prove_mhz_prover              TEXT,
  best_peak_prove_mhz_request_id          TEXT,
  best_effective_prove_mhz                BIGINT NOT NULL DEFAULT 0,
  best_effective_prove_mhz_prover         TEXT,
  best_effective_prove_mhz_request_id     TEXT,
  updated_at                              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_daily_market_period_timestamp ON daily_market_summary(period_timestamp DESC);

CREATE TABLE IF NOT EXISTS weekly_market_summary (
  period_timestamp                        BIGINT PRIMARY KEY,
  total_fulfilled                         BIGINT NOT NULL,
  unique_provers_locking_requests         BIGINT NOT NULL,
  unique_requesters_submitting_requests   BIGINT NOT NULL,
  total_fees_locked                       TEXT NOT NULL,
  total_collateral_locked                 TEXT NOT NULL,
  total_locked_and_expired_collateral     TEXT NOT NULL,
  p10_lock_price_per_cycle                TEXT NOT NULL,
  p25_lock_price_per_cycle                TEXT NOT NULL,
  p50_lock_price_per_cycle                TEXT NOT NULL,
  p75_lock_price_per_cycle                TEXT NOT NULL,
  p90_lock_price_per_cycle                TEXT NOT NULL,
  p95_lock_price_per_cycle                TEXT NOT NULL,
  p99_lock_price_per_cycle                TEXT NOT NULL,
  total_requests_submitted                BIGINT NOT NULL,
  total_requests_submitted_onchain        BIGINT NOT NULL,
  total_requests_submitted_offchain       BIGINT NOT NULL,
  total_requests_locked                   BIGINT NOT NULL,
  total_requests_slashed                  BIGINT NOT NULL,
  total_expired                           BIGINT NOT NULL DEFAULT 0,
  total_locked_and_expired                BIGINT NOT NULL DEFAULT 0,
  total_locked_and_fulfilled              BIGINT NOT NULL DEFAULT 0,
  locked_orders_fulfillment_rate          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  total_program_cycles                    TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  total_cycles                            TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  best_peak_prove_mhz                     BIGINT NOT NULL DEFAULT 0,
  best_peak_prove_mhz_prover              TEXT,
  best_peak_prove_mhz_request_id          TEXT,
  best_effective_prove_mhz                BIGINT NOT NULL DEFAULT 0,
  best_effective_prove_mhz_prover         TEXT,
  best_effective_prove_mhz_request_id     TEXT,
  updated_at                              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_weekly_market_period_timestamp ON weekly_market_summary(period_timestamp DESC);

CREATE TABLE IF NOT EXISTS monthly_market_summary (
  period_timestamp                        BIGINT PRIMARY KEY,
  total_fulfilled                         BIGINT NOT NULL,
  unique_provers_locking_requests         BIGINT NOT NULL,
  unique_requesters_submitting_requests   BIGINT NOT NULL,
  total_fees_locked                       TEXT NOT NULL,
  total_collateral_locked                 TEXT NOT NULL,
  total_locked_and_expired_collateral     TEXT NOT NULL,
  p10_lock_price_per_cycle                TEXT NOT NULL,
  p25_lock_price_per_cycle                TEXT NOT NULL,
  p50_lock_price_per_cycle                TEXT NOT NULL,
  p75_lock_price_per_cycle                TEXT NOT NULL,
  p90_lock_price_per_cycle                TEXT NOT NULL,
  p95_lock_price_per_cycle                TEXT NOT NULL,
  p99_lock_price_per_cycle                TEXT NOT NULL,
  total_requests_submitted                BIGINT NOT NULL,
  total_requests_submitted_onchain        BIGINT NOT NULL,
  total_requests_submitted_offchain       BIGINT NOT NULL,
  total_requests_locked                   BIGINT NOT NULL,
  total_requests_slashed                  BIGINT NOT NULL,
  total_expired                           BIGINT NOT NULL DEFAULT 0,
  total_locked_and_expired                BIGINT NOT NULL DEFAULT 0,
  total_locked_and_fulfilled              BIGINT NOT NULL DEFAULT 0,
  locked_orders_fulfillment_rate          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  total_program_cycles                    TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  total_cycles                            TEXT NOT NULL DEFAULT '000000000000000000000000000000000000000000000000000000000000000000000000000000',
  best_peak_prove_mhz                     BIGINT NOT NULL DEFAULT 0,
  best_peak_prove_mhz_prover              TEXT,
  best_peak_prove_mhz_request_id          TEXT,
  best_effective_prove_mhz                BIGINT NOT NULL DEFAULT 0,
  best_effective_prove_mhz_prover         TEXT,
  best_effective_prove_mhz_request_id     TEXT,
  updated_at                              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_monthly_market_period_timestamp ON monthly_market_summary(period_timestamp DESC);
