[package]
name = "boundless-povw-mint-calculator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
alloy-chains = { version = "0.2", default-features = false }
alloy-primitives = { version = "1.0" }
alloy-sol-types = { version = "1.0" }
boundless-povw-guests = { path = "..", default-features = false }
postcard = "1.1"
risc0-steel = { git = "https://github.com/risc0/risc0-ethereum", branch = "victor/patch-jul18" }
# TODO(povw): Use a released verion of risc0 here.
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "076da95cb879e5bcbf70b6586e9fad7a87e3914a", default-features = false, features = ["std", "unstable"] }

[patch.crates-io]
# enable RISC Zero's precompiles
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.1" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", tag = "tiny-keccak/v2.0.2-risczero.0" }
