// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant ECHO_ID = bytes32(0x37e05f394b58198b98b7e5584ddde8ddf50b18b63192bb4d2c8617c5681a6aaf);
    bytes32 public constant IDENTITY_ID = bytes32(0xb4805ec2db7eb6d287c31c3ecec5ba7e994f73ea9e5c22b7b86085ccd0a2c15d);
    bytes32 public constant LOOP_ID = bytes32(0x3c2acd1fa87aa85a91533a80c20f8e664f61cf84a4e48457754c3152061b30c6);
}
