secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAGl3Ck3jN3J70YiJ1ZaXCv8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkleamCTL5LfTIu5fAgEQgDtjGNFCmX9m3SwXQDDk1Ws/PFbJ7Cvhy3HnL5TM7982DBG8W/fW5d+ujqzyfOEX+MRMQAQr1jFhSFQwrw==
config:
  slasher:BASE_STACK: organization/bootstrap/services-staging
  slasher:BOUNDLESS_MARKET_ADDR: 0xBBA33Ecb04d06f116968C8137f78A82a4fc0c0D8
  slasher:CHAIN_ID: "84532"
  slasher:DOCKER_DIR: ../../
  slasher:DOCKER_TAG: latest
  slasher:ERROR_BALANCE_BELOW: "0.005"
  slasher:GH_TOKEN_SECRET:
    secure: v1:gBwVc9zYaf+42gmb:klcmoTNsc4nk6aMRUCFtaPqh0RTtdmdIU2GI7CS+ey9hEgFGTk+NFf2u6KNXjOEhhpUF2Wi6Rmuwf/VtKbCR2zR3z9Z9xlm4eCN8n750qiFGe+0kyH1sTPS/YJec75ZntlH4G4XaFqmCBmqorg==
  slasher:INTERVAL: "60"
  slasher:LOG_LEVEL: boundless_slasher=trace,boundless_market=debug
  slasher:MAX_BLOCK_RANGE: "500"
  slasher:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  slasher:PRIVATE_KEY:
    secure: v1:ohDwJN+g6aXZ7w9t:Gd7tyfMqMZ0fkA3P3SBT/6g8ju/TOjb30J3Du4A0u0/5+ezmhOslZK/3lrdlhJM8YPdMzurtM/zuGkGPAlVHZM8+94UC6rDZzafZFZ1o4/8=
  slasher:RETRIES: "5"
  slasher:SKIP_ADDRESSES: ""
  slasher:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-staging-launch
  slasher:TX_TIMEOUT: "120"
  slasher:WARN_BALANCE_BELOW: "0.01"
  slasher:ETH_RPC_URL:
    secure: v1:rx+I6n4r27Feca/Z:o1kOcwmcaLiulqVuH5rF9liRdwwIvuJJATZLZThJNv4Kab7eonGW2g85GEPJTPnPLsLHHnKQr1nJrsFIe/jl5QOb5hU3pdsHx2Ey
