secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAEOXY+6t9JVWEcjTPmYuSVtAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbYMJ+OsHe17c8UjlAgEQgDtIesDCqHJwIU89YfJpGQdEaIaFqp/82MbN7XHfYry1iHMHu0wBctYGnWJ3GtuGhnhqpjJJ2W2mIPvFyw==
config:
  slasher:BASE_STACK: organization/bootstrap/services-prod
  slasher:BOUNDLESS_MARKET_ADDR: 0x56da3786061c82214d18e634d2817e86ad42d7ce
  slasher:CHAIN_ID: "84532"
  slasher:DOCKER_DIR: ../../
  slasher:DOCKER_TAG: latest
  slasher:ERROR_BALANCE_BELOW: "0.005"
  slasher:GH_TOKEN_SECRET:
    secure: v1:4M+ezOZo5njO8KOP:nh3d3528HjnGaxX9bxVaoB55irD3Bvs2o337SAPhq5P+7wr7aK+658sUCf+Jcf5jCBBnOVMdGMo7D+lN4/aOQlwmz4XmrLTsi7WyE5mw47AXydednJMbpYhQylfyaX/w1G1wJt5gTeL7YVpuVA==
  slasher:INTERVAL: "60"
  slasher:LOG_LEVEL: boundless_slasher=trace,boundless_market=debug
  slasher:MAX_BLOCK_RANGE: "500"
  slasher:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  slasher:PRIVATE_KEY:
    secure: v1:ZV7wDz4Xvj2+hMRT:acNI1bClNKzLu5H2pC2nManyyWL0TXHcp2pWJEhqWJ57rco7MFB39YWOe9qAwuNrGSRpGiNUMwxUaVzKRMc/3UeclzSc+kU19OTyJF2yCCg=
  slasher:RETRIES: "5"
  slasher:SKIP_ADDRESSES: ""
  slasher:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-launch
  slasher:TX_TIMEOUT: "120"
  slasher:WARN_BALANCE_BELOW: "0.01"
  slasher:ETH_RPC_URL:
    secure: v1:wAsRjI7XJEMau9IA:D5sPvcGjHe7bKMk/N6OYwnh7oiMpsrrnuJPYEsfW97M7QUIEmYrNH4FuWNWrLri2Do1y9OQEVjHoJ9KuRYoHlqGjAGaqXBUwMNOI
