[package]
name = "workflow-common"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[dependencies]
anyhow = { workspace = true }
aws-sdk-s3 = { workspace = true }
bincode = { workspace = true }
lazy_static = "1.4"
prometheus = "0.13"
prometheus_exporter = { workspace = true }
risc0-zkvm = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
