[package]
name = "methods"
version = { workspace = true }
edition = { workspace = true }

[build-dependencies]
hex = { workspace = true }
risc0-build = { workspace = true }
risc0-build-ethereum = { workspace = true }

[package.metadata.risc0]
methods = ["guests"]
