[package]
name = "eigen"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
risc0-zkvm = { workspace = true, default-features = true }
serde = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
methods = { workspace = true }
serde_json = { workspace = true }
test-log = { workspace = true }

[features]
default = []
