[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[workspace]

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
risc0-zkvm = { version = "1.2", default-features = false, features = ["std"] }
