// Copyright 2026 Boundless Foundation, Inc.
//
// Use of this source code is governed by the Business Source License
// as found in the LICENSE-BSL file.
// SPDX-License-Identifier: BUSL-1.1

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"62f049f609e5e571a5daab1c3a3c4e02e4e3f3104218cb0bc39a1067859858d09eefd9102809fbb55dd140c09cf131dae9c271d7d386b021389e929f791e7aa4ffdb90741b8f4159cc9d57fce7c4bb5a7da795cb15cd35da3f1067218e1359fe2430af2b24b5ac63cdaf40cdb240039372942207e1432496eb7efa4dec0cee4bef90cece1ae0027bc89807ac1293ce8d9c8ce3dd999f6926ea0b5904acd0182c85a203b325b504efe9bcef7d9dca9cbf7f2d1b312bd189352e7a50a969b2175dc3a3079615a8fa448aba2fc439af0a5f01949a47507210c5f3088a485ecbe6c4343e7227145675020b043e2b1211be05c0dbab20d5e5423b5b53d193b7a8cb91455dca86";
    bytes32 public constant CLAIM_DIGEST = hex"00518e3981d8f63a944afd3d1d2b5c23ba7968488981875b7659e1beb2a95a63";
}
