[alias]
xtask = "run --manifest-path xtask/Cargo.toml --package xtask --release --"
xtask-setup-blake3-groth16 = "run --manifest-path xtask/Cargo.toml --package xtask --no-default-features -F cuda --release -- setup-blake3-groth16"

[target.x86_64-unknown-linux-gnu]
# Use mold for faster linking on Linux hosts/builders where it is installed.
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
