[package]
name = "guest-util"
version = "0.1.0"
edition = "2021"

[build-dependencies]
hex = { workspace = true }
risc0-build = { workspace = true }
risc0-build-ethereum = { workspace = true }

[package.metadata.risc0]
methods = ["echo", "identity"]
