[package]
name = "indexer-api"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[dependencies]
# Core dependencies
alloy = { workspace = true, default-features = false }
anyhow = { workspace = true }
aws-config = { version = "1.6", features = ["behavior-version-latest"] }

# Lambda runtime
lambda_runtime = "0.13.0"
lambda_http = "0.13.0"

# Web framework
axum = { version = "0.7", features = ["macros"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = "0.9"

# Database
sqlx = { workspace = true, features = [ "any", "postgres", "sqlite", "runtime-tokio", "json", "migrate", "macros", "runtime-tokio-rustls"] }

# Fix cross-compilation for Lambda
openssl = { version = "0.10", features = ["vendored"] }

# Async runtime
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "env-filter",
] }

# Internal dependencies
boundless-indexer = { path = "../../indexer" }

[dev-dependencies]
# HTTP client for integration tests
reqwest = { version = "0.12", features = ["json"] }
# Async runtime for tests
tokio = { workspace = true, features = ["test-util"] }