// Copyright 2026 Boundless Foundation, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::{fs, path::Path, process::Command};

use blake3_groth16::compress_blake3_groth16;
use boundless_market::selector::SelectorExt;
use clap::Parser;
use guest_util::ECHO_ELF;
use regex::Regex;
use risc0_circuit_recursion::control_id::{ALLOWED_CONTROL_ROOT, BN254_IDENTITY_CONTROL_ID};
use risc0_zkvm::{default_prover, Digest, ExecutorEnv, ProverOpts};

#[derive(Debug, Parser)]
pub struct BootstrapBlake3Groth16 {
    /// blake3-groth16 setup directory
    #[arg(long, env)]
    blake3_groth16_setup_dir: String,
}

const SOL_HEADER: &str = r#"// Copyright 2026 Boundless Foundation, Inc.
//
// Use of this source code is governed by the Business Source License
// as found in the LICENSE-BSL file.
// SPDX-License-Identifier: BUSL-1.1

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

"#;

const SOLIDITY_VERIFIER_TARGET: &str = "contracts/src/blake3-groth16/Groth16Verifier.sol";
const SOLIDITY_CONTROL_ID_PATH: &str = "contracts/src/blake3-groth16/ControlID.sol";
const SOLIDITY_TEST_RECEIPT_PATH: &str = "contracts/test/receipts/Blake3Groth16TestReceipt.sol";
const RUST_VERIFIER_PATH: &str = "blake3_groth16/src/verify.rs";

impl BootstrapBlake3Groth16 {
    pub async fn run(&self) {
        let current_dir = std::env::current_dir().unwrap();
        let blake3_setup_path = current_dir.join(&self.blake3_groth16_setup_dir);
        bootstrap_verifying_key(&blake3_setup_path);
        bootstrap_control_id();
        bootstrap_test_receipt().await;
    }
}

fn bootstrap_verifying_key(blake3_setup_path: &Path) {
    let solidity_verifier_target = Path::new(SOLIDITY_VERIFIER_TARGET);
    let solidity_verifier_source = blake3_setup_path.join("verifier.sol");
    std::fs::copy(&solidity_verifier_source, solidity_verifier_target).unwrap();
    let solidity_code = fs::read_to_string(solidity_verifier_source).unwrap();
    let mut rust_code = fs::read_to_string(RUST_VERIFIER_PATH).unwrap();

    let solidity_constants = [
        "alphax", "alphay", "betax1", "betax2", "betay1", "betay2", "gammax1", "gammax2",
        "gammay1", "gammay2", "deltax1", "deltax2", "deltay1", "deltay2", "IC0x", "IC0y", "IC1x",
        "IC1y",
    ];

    let rust_constants = [
        "ALPHA_X", "ALPHA_Y", "BETA_X1", "BETA_X2", "BETA_Y1", "BETA_Y2", "GAMMA_X1", "GAMMA_X2",
        "GAMMA_Y1", "GAMMA_Y2", "DELTA_X1", "DELTA_X2", "DELTA_Y1", "DELTA_Y2", "IC0_X", "IC0_Y",
        "IC1_X", "IC1_Y",
    ];

    for (i, constant) in solidity_constants.into_iter().enumerate() {
        let re = Regex::new(&format!(r"uint256 constant\s+{constant}\s*=\s*(\d+);")).unwrap();
        if let Some(caps) = re.captures(&solidity_code) {
            let rust_re =
                Regex::new(&format!("const {}: &str =[\\r\\n\\s]*\"\\d+\";", rust_constants[i]))
                    .unwrap();
            rust_code = rust_re
                .replace(
                    &rust_code,
                    &format!("const {}: &str = \"{}\";", rust_constants[i], &caps[1]),
                )
                .to_string();
        } else {
            println!("{constant} not found");
        }
    }

    fs::write(RUST_VERIFIER_PATH, rust_code).unwrap();

    // Use rustfmt to format the file.
    Command::new("rustfmt")
        .arg(RUST_VERIFIER_PATH)
        .status()
        .unwrap_or_else(|_| panic!("failed to format {RUST_VERIFIER_PATH}"));
}

fn bootstrap_control_id() {
    const LIB_HEADER: &str = r#"pragma solidity ^0.8.9;

 library ControlID {
"#;
    let control_root =
        format!(r#"bytes32 public constant CONTROL_ROOT = hex"{ALLOWED_CONTROL_ROOT}";"#);
    let mut bn254_control_id = BN254_IDENTITY_CONTROL_ID;
    // NOTE: The solidity verifier interprets it as a uint256 and expects the opposite byte order.
    bn254_control_id.as_mut_bytes().reverse();
    let bn254_control_id = format!(
        r#"// NOTE: This has the opposite byte order to the value in the risc0 repository.{}bytes32 public constant BN254_CONTROL_ID = hex"{}";"#,
        "\n",
        hex::encode(bn254_control_id)
    );
    let content = &format!("{SOL_HEADER}{LIB_HEADER}\n{control_root}\n{bn254_control_id}\n}}");
    let solidity_control_id_path = Path::new(SOLIDITY_CONTROL_ID_PATH);
    fs::write(solidity_control_id_path, content).unwrap_or_else(|_| {
        panic!("failed to save changes to {}", solidity_control_id_path.display())
    });

    // Use forge fmt to format the file.
    Command::new("forge")
        .arg("fmt")
        .arg(solidity_control_id_path.as_os_str())
        .status()
        .unwrap_or_else(|_| panic!("failed to format {}", solidity_control_id_path.display()));
}

async fn bootstrap_test_receipt() {
    const LIB_HEADER: &str = r#"pragma solidity ^0.8.13;

 library TestReceipt {
"#;
    let (seal, claim_digest) = generate_receipt().await;
    let selector = format!("{:x}", SelectorExt::blake3_groth16_latest() as u32);
    let seal = hex::encode(&seal);

    // NOTE: Selector value is the first four bytes of the verifier param digest. It is added as part
    // of ABI encoding and used for routing to the correct verifier on-chain. We do not use the
    // full ABI encoding implementation here because its part of risc0-ethereum-contracts, which
    // would be a hassle to import.
    let seal = format!(r#"bytes public constant SEAL = hex"{selector}{seal}";"#);
    let claim_digest = format!(r#"bytes32 public constant CLAIM_DIGEST = hex"{claim_digest}";"#);

    let solidity_test_receipt_path = Path::new(SOLIDITY_TEST_RECEIPT_PATH);
    let content = &format!("{SOL_HEADER}{LIB_HEADER}\n{seal}\n{claim_digest}\n}}");
    fs::write(solidity_test_receipt_path, content).unwrap();

    // Use forge fmt to format the file.
    Command::new("forge").arg("fmt").arg(solidity_test_receipt_path.as_os_str()).status().unwrap();
}

// Return a Blake3-Groth16 `seal` and the claim digest.
// Requires running Docker.
async fn generate_receipt() -> (Vec<u8>, Digest) {
    tracing::info!("prove");
    let input = [3u8; 32];

    let env = ExecutorEnv::builder().write_slice(&input).build().unwrap();
    tracing::info!("Proving echo program to get initial receipt");
    let prover = default_prover();
    // Produce a receipt by proving the specified ELF binary.
    let receipt = prover.prove_with_opts(env, ECHO_ELF, &ProverOpts::succinct()).unwrap().receipt;
    tracing::info!("Initial receipt created, compressing to blake3_groth16");
    let blake3_receipt = compress_blake3_groth16(&receipt).await.unwrap();
    let seal = blake3_receipt.seal().expect("failed to retrieve seal");
    let claim_digest = blake3_receipt.claim_digest().expect("failed to compute claim digest");
    (seal.clone(), claim_digest)
}
