---
all:
  hosts:
    localhost:
      ansible_connection: local
    prover-01:
      ansible_host: 64.34.93.87
      ansible_user: ubuntu
    prover-02:
      ansible_host: 64.34.93.83
      ansible_user: ubuntu
