---
- name: Deploy Prover with Docker Compose
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Deploy Prover Docker Compose Stack
      ansible.builtin.include_role:
        name: prover
      tags:
        - prover
