config:
  aws:region: us-west-2
  order-generator-base:BASE_STACK: organization/bootstrap/services-dev
  order-generator-base:BOUNDLESS_MARKET_ADDR: 0x2d124b86179F0De2d5B7A75E4dcD7e35a3363B16
  order-generator-base:SET_VERIFIER_ADDR: 0xEf0A93B2310d52358F1eCA0C946aD7D25596e7dd
  order-generator-base:DOCKER_DIR: ../../
  order-generator-base:DOCKER_TAG: latest
  order-generator-base:LOG_LEVEL: debug
  order-generator-base:PINATA_GATEWAY_URL: https://indigo-quickest-hamster-225.mypinata.cloud
  order-generator-base:CHAIN_ID: "11155111"
  order-generator-simple:INTERVAL: "300"
  order-generator-simple:LOCK_STAKE: "0.1"
  order-generator-simple:MAX_PRICE_PER_MCYCLE: "0.001"
  order-generator-simple:MIN_PRICE_PER_MCYCLE: "0.000005"
  order-generator-simple:RAMP_UP: "600"
  order-generator-zeth:SCHEDULE_MINUTES: "10"
  order-generator-zeth:RETRIES: "2"
  order-generator-zeth:INTERVAL: "1800"
  order-generator-zeth:LOCK_STAKE: "0.1"
  order-generator-zeth:RAMP_UP: "600"
  order-generator-zeth:MIN_PRICE_PER_MCYCLE: "0.000001"
  order-generator-zeth:MAX_PRICE_PER_MCYCLE: "0.001"
  order-generator-zeth:TIMEOUT: "1000"
  order-generator-zeth:LOCK_TIMEOUT: "500"
encryptionsalt: v1:78M4I62y8LA=:v1:AlO8AF//VJjVKLbB:AGh1jNpKbDPMsX+Zd0onAOwdWS7d7A==
