sources:
  journald:
    type: journald
    include_units:
      - bento.service
      - bento-broker.service

transforms:
  extract_message:
    type: remap
    inputs: ["journald"]
    source: |
      . = .message

sinks:
  cloudwatch_bento:
    type: aws_cloudwatch_logs
    inputs: ["extract_message"]
    group_name: "/boundless/bento/${STACK_NAME}"
    stream_name: "%Y-%m-%d"
    region: "us-west-2"
    encoding:
      codec: json

