[api]
enabled = true
address = "127.0.0.1:9001"

[sources.journald]
type = "journald"
include_units = [
    "bento.service",
    "bento-api.service",
    "bento-broker.service",
    "systemd-*"
]

[transforms.bento_executor_logs]
type = "remap"
inputs = ["journald"]
source = '''
if .SERVICE == "bento-executor.service" {
    . = parse_json!(.message)
    .timestamp = now()
    .service = "bento-executor"
    .instance_id = get_env_var!("HOSTNAME")
    .level = .level || "info"
} else {
    . = null
}
'''

[transforms.bento_aux_logs]
type = "remap"
inputs = ["journald"]
source = '''
if .SERVICE == "bento-aux.service" {
    . = parse_json!(.message)
    .timestamp = now()
    .service = "bento-aux"
    .instance_id = get_env_var!("HOSTNAME")
    .level = .level || "info"
} else {
    . = null
}
'''

[transforms.bento_prover_logs]
type = "remap"
inputs = ["journald"]
source = '''
if .SERVICE == "bento-prover.service" {
    . = parse_json!(.message)
    .timestamp = now()
    .service = "bento-prover"
    .instance_id = get_env_var!("HOSTNAME")
    .level = .level || "info"
} else {
    . = null
}
'''

[transforms.bento_api_logs]
type = "remap"
inputs = ["journald"]
source = '''
if .SERVICE == "bento-api.service" {
    . = parse_json!(.message)
    .timestamp = now()
    .service = "bento-api"
    .instance_id = get_env_var!("HOSTNAME")
    .level = .level || "info"
} else {
    . = null
}
'''

[transforms.bento_broker_logs]
type = "remap"
inputs = ["journald"]
source = '''
if .SERVICE == "bento-broker.service" {
    . = parse_json!(.message)
    .timestamp = now()
    .service = "bento-broker"
    .instance_id = get_env_var!("HOSTNAME")
    .level = .level || "info"
} else {
    . = null
}
'''

[sinks.cloudwatch_bento_api]
type = "aws_cloudwatch_logs"
inputs = ["bento_api_logs"]
group_name = "/boundless/bento/api"
stream_name = "${HOSTNAME}"
region = "us-west-2"
encoding.codec = "json"

[sinks.cloudwatch_bento_broker]
type = "aws_cloudwatch_logs"
inputs = ["bento_broker_logs"]
group_name = "/boundless/bento/broker"
stream_name = "${HOSTNAME}"
region = "us-west-2"
encoding.codec = "json"

[sinks.cloudwatch_bento_executor]
type = "aws_cloudwatch_logs"
inputs = ["bento_executor_logs"]
group_name = "/boundless/bento/executor"
stream_name = "${HOSTNAME}"
region = "us-west-2"
encoding.codec = "json"

[sinks.cloudwatch_bento_aux]
type = "aws_cloudwatch_logs"
inputs = ["bento_aux_logs"]
group_name = "/boundless/bento/aux"
stream_name = "${HOSTNAME}"
region = "us-west-2"
encoding.codec = "json"

[sinks.cloudwatch_bento_prover]
type = "aws_cloudwatch_logs"
inputs = ["bento_prover_logs"]
group_name = "/boundless/bento/prover"
stream_name = "${HOSTNAME}"
region = "us-west-2"
encoding.codec = "json"
