---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Bento
  listen:
    - "Restart Bento"
    - "Restart docker"
  ansible.builtin.command:
    cmd: systemctl restart --no-block bento
