---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Bento
  listen:
    - "Restart Bento"
    - "Restart docker"
  ansible.builtin.systemd:
    name: bento
    state: restarted
    daemon_reload: true
  async: 3600
  poll: 15
