---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Bento
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl restart --no-block bento
  changed_when: true
