secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHjo9dP83MIkRU7zP48vJb5veObMz9xpFGm6gYEXRHbpqwH3SbgmxhQeaS1Y7akbV0SIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMv/MnvVIXbiQq54+5AgEQgDtJBBUVluV3BGq00i4UHg9r91C1wznzrDHTywcDFNVY8oBrPohvvuk4hFep7hLCyp2DU3/oMnRlGtoCKA==
config:
  aws:region: us-west-2
  order-stream:BASE_STACK: organization/bootstrap/services-staging
  order-stream:BOUNDLESS_ADDRESS: 0x60d11ef5d4608bab18a663fd486d3b9f162172cf
  order-stream:BYPASS_ADDRS: 0x821Abe5Dfa67c08af9a67C344C3b2651F7960136
  order-stream:CHAIN_ID: "167000"
  order-stream:CI_CACHE_SECRET:
    secure: v1:pJAlHd4Bkitr5ANB:a/McUdaet7jYmYJw5VcWRkUciZWP6w5DGET/B1NfaMIV5fH28O1RfZMicx2GX3Epue4g2jdm/3NzXWKFG4Tu86s4C5kwHcYLp+4PCAl8jtaz6e5k7dvXOUH+XUbZOMAEEkwNEFTwelOWlStPLjVT5DQAiXruh6vW0W/MFeFWWA==
  order-stream:DOCKER_DIR: ../../
  order-stream:DOCKER_TAG: latest
  order-stream:GH_TOKEN_SECRET:
    secure: v1:9qM9PiQiLDwk7XRl:awC475v/s72GfjPjHnpg3ct9iC3USqZQmF/Itfv8ZuS8Ik70LceKmuMfSGkmUalJW8eOZ1sKYoPa2C4YjFXIfHSABrcvptQwlfdK0eBJhukpIsR/vn3NwuZt5SRzv/63foG3ArYp/Cgcfqub7w==
  order-stream:MIN_BALANCE_RAW: "5000000000000000000"
  order-stream:ORDER_STREAM_PING_TIME: "100"
#  order-stream:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  order-stream:PREMIUM_API_KEY:
    secure: v1:XTaGKHuTJqkQIk0F:KwUYIPzyBU8VM1u6KKhXigolA24uGSNhnYivowB2
  order-stream:RDS_PASSWORD:
    secure: v1:BCi+e8GtkCmNm8mT:ap/870QxEaG3ceVvWT0/yZBGOTJyukywOvFV6STsQ2g0nw==
  order-stream:REDSHIFT_ADMIN_PASSWORD:
    secure: v1:mtUljTgAgUqvqC18:M79Ps5yNnmLSeqirxl98Dg8UHOZ1IC3E2Xl6XQ==
  order-stream:REDSHIFT_READONLY_PASSWORD:
    secure: v1:JYjK1WFwQ3lsuVJh:6cuBP82TQgkvU1nFShPJyzdVJVuV0kzOzPq91w==
#  order-stream:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-staging-launch
  order-stream:ETH_RPC_URL:
    secure: v1:f1BqdkYofm4y6DY0:h0BVuwZHHoVfg1TTHBS4rodxb2ULGGu6DHrGq2WyNF4j77UzH1aZD0+vGtUm
