secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAFQfqrqj96+KQNWDlATlkjzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPTevy04CUnR0SSgVAgEQgDsqSU90TTc5dX72bpdqcXLOykxCTrfkD9hoh1UJX2I3oO+Hw6DwWBArtk+g3tpB2zJKBlrwTV4o7LkdJA==
config:
  distributor:BASE_STACK: organization/bootstrap/services-prod
  distributor:CHAIN_ID: "8453"
  distributor:DISTRIBUTOR_ADDRESS: 0xd79A4B9D713e70De8b0B820eBB7B5a18B7F07d4A
  distributor:DISTRIBUTOR_PRIVATE_KEY:
    secure: v1:auASbUZzUFxOqohn:J8HdTU+iQwDYeFVl8LA10/y2Q//CM0+xIfMMorPs8w6dRC97a0o9beLas2Sy3btcgiWGJxR+K+kC0amDzMBai7jcoNirQpPO0PXowkstxTM=
  distributor:DOCKER_DIR: ../../
  distributor:DOCKER_TAG: latest
  distributor:ETH_THRESHOLD: "0.03"
  distributor:ETH_TOP_UP_AMOUNT: "0.07"
  distributor:GH_TOKEN_SECRET:
    secure: v1:T9tEHTIk9hUGTtwo:aflzidGNMvOAqHfZdc8QwoQ3MEt8g87xA+0e6769hmKX6RAbO9i3Tz0pVzz2mBt8CLguZxGDNQH83ioEY1A1KF8iLEjJAzt0D8Itqc0k6pdrg00SmGWcSauS9cDibcVtYrCPpMl2KhWmWmnU5w==
  distributor:LOG_LEVEL: "info,boundless_market=debug"
  distributor:ORDER_GENERATOR_KEYS:
    secure: v1:HPMMMYokLVCjxO3+:CYFPrcsQ600CV1KbXFMcUQfIALfM8EOd0KA6tXFTk/w5K8lNGCDeAFk2mcRBntWRwMULTJygXOW2q/B95alb9hzaar46S9+nxqZQIscKHijCfnExhKoQ2pOBxOOkUMADP/p6FJ3u5Xdy0qK9+NgiK0xKkkUs+kEcTxHegUK1ETQFqglgXRPbkM9IhNvyjak6q+CyRkX2OfEUP+nJFksavjoSLWaQZQB+Qx+VzzJpDFxnHTB0aP+D6dzyldzp3e2a1+IGMReDHzNxIcg+F3ye2nnHnxCoZ0YmHUMkx1YJEUSYfE9uL2SXt3OrhlN1BvrqP+x7xPDlEr+Lo8/zLXxSOX0EI6IKOX9CST2CBYchzN2MRZ8O4HbhR+swpWJEIJHEDG1Er+7Md5VP4LkU6umIfN3w9j9g3cTNnAQF08sSD/kJcy9PEGLL7Mx4nEMYGxdYSXV1gA==
  distributor:OFFCHAIN_REQUESTOR_ADDRESSES: "0xc197ebe12c7bcf1d9f3b415342bdbc795425335c,0xf353bda16a83399c11e09615ee7ac326a5a08ccf"
  distributor:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  distributor:PROVER_ETH_DONATE_THRESHOLD: "0.15"
  distributor:PROVER_KEYS:
    secure: v1:fQWHaSbC5wXEFZH8:9rxOJTCq+kaOKdEzTsUUg3GAh3tevAoytW57Y9t3JIMDhyf5wqt3xh4cXe2xoyFAxlvnWvPYq8+CinM9EMScO3eQ2R7u4UxayUmJFxbKNWCcwYq+Rtd35rKWuLScWQK3QVy7UDIezjjFZ+LF7+xgXbx5UmmRcRqo+Ur9BBq0mrP8QEFgSnRIzlJLe2MdmMJwoQ==
  distributor:PROVER_STAKE_DONATE_THRESHOLD: "150.0"
  distributor:SCHEDULE_MINUTES: "90"
  distributor:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-launch
  distributor:SLASHER_KEY:
    secure: v1:XBrxv0bakL92pjka:Zaw0da9L5v0rFJYJ03owljQkhjwAaNw5VbCdkSAwCj0REkN9Wz7cwVKRsicG86UjusQH4mVeVz6omfiOJJKiBGdULROheWu49FpU3uDFI3U=
  distributor:STAKE_THRESHOLD: "5"
  distributor:STAKE_TOP_UP_AMOUNT: "10"
  distributor:ETH_RPC_URL:
    secure: v1:E1WuDwMATaOQ6GEE:y8KpEhqaQwjYWkPUmoYNGjuJZTMXmoXcnGyZcECvwkoHjbtA5og5ShcIRcEw2InPOagemm79RIvUAKIWlRthzqBlPXY6gL9eRxwQ
  distributor:DISTRIBUTOR_ETH_ALERT_THRESHOLD: "0.5"
  distributor:DISTRIBUTOR_STAKE_ALERT_THRESHOLD: "200.0"