secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAEIqCF3qEbqpZTomvgjkbLPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRLtFBtAN1/DhJ3wuAgEQgDucHwLVOOrV+VNFT6WUQIk0JmggV64j3JtYyEmB3L8Be1MHKCTHDyaqCpeooWnZrZdd6E/KXaFhnIGoQw==
config:
  distributor:CHAIN_ID: "8453"
  distributor:DISTRIBUTOR_ADDRESS: 0xFc1f6D609610a479F9c7453BF3aeC8cb3849F865
  distributor:DISTRIBUTOR_PRIVATE_KEY:
    secure: v1:wsMaM6eH71PkGoGO:gnW40haQnOPc/SUZaxWYyvQY4tJNe7qjkn7rgbszPuaPczv607usL0t6mXGNtCCTF2uGUaYp6q8TobbS48GS5du7EL3FVm2l3uGGOxSemok=
  distributor:ETH_THRESHOLD: "0.02"
  distributor:ETH_TOP_UP_AMOUNT: "0.04"
  distributor:GH_TOKEN_SECRET:
    secure: v1:sFcUNPOUWZ1ghOjf:Y3a6CP7X6bTABqL+OxMTKA7yzNFptTWH2+ADn188fYxHTccf0qeaIF8VRfCvJ2iVnMxfoAFsMpW72mf+Gzv3seAzwLHZhbwciJ4WrFKD3bHKydiDAQepnRbogHwcMfGWi7hSkSu72ihW3sm/hQ==
  distributor:ORDER_GENERATOR_KEYS:
    secure: v1:A7pRfmI8E5lTwTdP:btH/PlOEoOg6s5sPGwD6DYaKkq2lcqTmvXMo2An7nL3y2ar9ja/sH1RlUBhBhAMHen6bMuenWPLtd1G8FE3oxpupu/DZLm7WukjVhdWfcdqS7sTlEKM0kg2hs2esyqosw8p1x1Of/kbMftgclV4yzKlHPETrPTnevkFwyc9AcYQRu/EqjxaQmvNTSWi8aoTBBzTmHqzm6g4JTo6ykEW++nZlYwvrSgfkklP6WvLstvnZzlPrc+sTW0bEMsKsJl3KLuAiVOQGAJ2dD9w7u9nFsn9OinoPz9tgMrhpoqXFx3ZriA7U75wxQYgFZl3+FYbKvLLYDdVsJN9VkYHTBev7Txjr/M2fJdabplvBimCSgPaJCeqqHemh2T0H/pv3wOTeUXzlDkr9iIHwz8o4iv3HBlmW8D9Md2547Esz/mGKgLYUVLiidY9Zd/f09b0fc/252WHZ+B2+nj9SRLoOzAsK6mTssvdyRyzKZZnp6C+vsmBbK47VuyG5c7pK9HYlKbF2hZCwAU4HiBZGM7PsOqzS+Dq2bc2I
  distributor:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  distributor:PROVER_ETH_DONATE_THRESHOLD: "0.02"
  distributor:PROVER_KEYS:
    secure: v1:EY44pcRVdz2JuCTu:zCzN/MYur9seJdgg5lHbUQ7KoBWjAwEOmVSTNTTo1eqjVwdnREY7CvniVRO9PqEJJweMlxo1Gw8GcaZ2JPUcqGiU4ha7FVXrKDGfhNrIWcAO6IRJ2WAneHwKGBQRIjSMvuYsKXJhPQXzvTjklbKKeAMvGuaDKGM28uUEXSDHzmEYmWz4CEYWs8GHGrx+kje/wQ==
  distributor:SCHEDULE_MINUTES: "240"
  distributor:PROVER_STAKE_DONATE_THRESHOLD: "150.0"
  distributor:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-prod
  distributor:SLASHER_KEY:
    secure: v1:5h1orYNX17m3Vp3b:R1yCFR4Yks5rPn7nMs180Y7LOHPcksMwlSPBwsZz2sfUrlmpTfWXxlpv5nIewPuy89aAAS2pJQtoybTC+yGCQG50GN4xAaMw9pMPjkIGMys=
  distributor:STAKE_THRESHOLD: "25"
  distributor:STAKE_TOP_UP_AMOUNT: "35"
  distributor:ETH_RPC_URL:
    secure: v1:Ft8qHrOPQTypWl6L:7O1I0MEZmsPG/ptdueEjY1+NyaQf5SWILbDy2B6KWJqN5rmuM1l5FLy9KpsMnwjGinbCMWxEC97eawyILp6LluqF3yYeEzxBKD4e
  distributor:LOG_LEVEL: "info"
  distributor:DOCKER_DIR: ../../
  distributor:DOCKER_TAG: latest
  distributor:BASE_STACK: organization/bootstrap/services-prod
