[package]
name = "taskdb-redis"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
redis = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
uuid = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "postgres",
  "uuid",
  "macros",
  "bigdecimal",
  "chrono",
  "migrate",
  "json",
  "tls-rustls",
] }
clap = { workspace = true, features = ["derive"] }
criterion = { version = "0.5", features = ["async_tokio"] }
rand = "0.9.1"
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
