name: cw-monitoring
description: CloudWatch monitoring stack for Latitude bare-metal nodes
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
