name: Release

on:
  push:
    tags:
      - "v*.*.*"
  # for testing purposes
  pull_request:
    branches: [main, "release-*"]

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  release:
    runs-on: [self-hosted, Linux, X64, prod, cpu]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: install rust
        uses: risc0/risc0/.github/actions/rustup@release-1.1
        with:
          toolchain: '1.79'

      - name: setup sccache + s3
        uses: ./.github/actions/sccache

      - name: install cargo risczero
        uses: ./.github/actions/bininstall-risc0
        with:
          risczero-version: '1.1'
          toolchain-version: 'r0.1.79.0-2'

      - name: cargo build
        run: cargo build
        env:
          RISC0_USE_DOCKER: 1

      - name: image ID check
        run: bash image-id-check.sh