// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant ECHO_ID = bytes32(0x02df794e2f0c80466904d709d2adc4e529df5ceb375b4b65a84ad330193512de);
    bytes32 public constant IDENTITY_ID = bytes32(0x4098bd812f6d696b8415112737a5d303146a3c5683d73d7175e8b856bc27fbae);
}
