secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHjo9dP83MIkRU7zP48vJb5veObMz9xpFGm6gYEXRHbpqwHNpVz9SwZmm7sXCROBDP+OAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEqHuY1vOYpFqHvcGAgEQgDuelOP8/WrDZMuIwbkxMn7STSUIfC36T9oY5CBMrgwYKsfUw0MVDlyY276gF3JkYAtz5MB6LeV6+ebUWw==
config:
  aws:region: us-west-2
  indexer:ALLOWED_IP_ADDRESSES:
    secure: v1:Zz+pGPqe/bRNXYFa:3k3mZ6Bb2bPlKMXB/1+8j7U4ou257c5MZ5EwOEx5Sxw=
  indexer:BACKFILL_CHAIN_DATA_BLOCKS: "100"
  indexer:BASE_STACK: organization/bootstrap/services-prod
  indexer:BENTO_API_KEY:
    secure: v1:DxdBaElemluc1Ylr:oaShb1JN1VP+y3h+JHUIjTizb5b1c3lRyP7lJiXSGOqtqy5X4vdaFkdy0JgJBmNrUrFfSK4HLKIjEQ==
  indexer:BENTO_API_URL:
    secure: v1:wldS7E9d2Dsyf9Tw:iIT1Zf4MGJUHjbJTKUsyIefXCfV37gbtEioHZnfqARBqR5JzNw9E7vp/rxKVrFFM6Hxi
  indexer:BLOCK_DELAY: "10"
  indexer:BOUNDLESS_ADDRESS: 0xb3f5c7b4379052eade8c7f3fa6da37fb871da28b
  indexer:CHAIN_DATA_BATCH_DELAY_MS: "2500"
  indexer:CHAIN_ID: "167000"
  indexer:CI_CACHE_SECRET:
    secure: v1:Ce/EF0AOVWl5PlJo:4sRd34ApwhznNOB6K2Xn+j36llDj1E3q8TsF7z7lbyB1XmIdyRfxT3KKjf0nJ969LRsCyUYg/LO7LkKxOuHeZa1RSM8joWU+qyxWbHCT8OPXjvIpX79d/QGe+Gv7ykzk7F5mk/65idVtBOP732KaIJlbrw+I0T3Fd3kVQ6aNpQ==
  indexer:DOCKER_DIR: ../../
  indexer:DOCKER_TAG: latest
  indexer:GH_TOKEN_SECRET:
    secure: v1:JFRwG3DxSw4LjTTb:dPAHMC1pm1uAppTMEgMJJne+A2Nx5e9deZvXrmjvWpNuMWYQAu3ojsqdXdPaRALZGKUEhGAqNW4m37uK73A9FFM1T98NsnlZ87IPXSUpSxjef7mwG1xmQl0YU7ou6UlJ5vshOB8xxOaNk0WEvA==
  indexer:ORDER_STREAM_API_KEY:
    secure: v1:qTzaa6ZO6tYwwoJW:j7YHDRhdaR2uw8T3QPaSIi4rbqMdV6qo33LhVGtq
  indexer:ORDER_STREAM_URL: https://base-mainnet.boundless.network
  indexer:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  indexer:PREMIUM_API_KEY:
    secure: v1:Y00nS3KCxjWWjwWe:ezL5nI6jaVjGxL5lvyEJ9XWjFamWQYUuRDtQHw==
  indexer:PROXY_SECRET:
    secure: v1:zUdi2ECTnJtV0Hui:ACxqRxNOCd+8udlS1noGnHFyUMJfxdFI2IH1uwDjGNNxN6PaLI9Wjg==
  indexer:RDS_PASSWORD:
    secure: v1:GMbRbU4TXOoeektZ:df31w7J0hlyAraiX2Q/UCeY36Zeyz3tqcP6dYQJAGn89Aw==
  indexer:RUST_LOG_API: debug
  indexer:RUST_LOG_INDEXER: info,boundless_indexer=debug
  indexer:RUST_LOG_MONITOR: info,indexer_monitor=debug
  indexer:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-launch
  indexer:START_BLOCK: "4819525"
  indexer:ETH_RPC_URL:
    secure: v1:963FN/eaUjMwP98W:beq6It7VvaH4v3ppFmJ+OCpOFJUBtUJi6bbm+yofvl+d+HsUVwvhdCY9P7yJ
