secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAFQnk96iZHiItdiUZmrd88tAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGhehmjsbmGMGlRnGAgEQgDv42AX54nZr+dX2jdLRIXDee3XtxfFc7h/12+wQVGXqMF+AmI0dHi98MlAyC+36WTZhDOM6cpHP34xSoQ==
config:
  aws:region: us-west-2
  indexer:BASE_STACK: organization/bootstrap/services-prod
  indexer:BOUNDLESS_ADDRESS: 0x006b92674E2A8d397884e293969f8eCD9f615f4C
  indexer:DOCKER_DIR: ../../
  indexer:DOCKER_TAG: latest
  indexer:START_BLOCK: 8137095
  indexer:ETH_RPC_URL:
    secure: v1:0j7+fwrATMUU0iT8:73Z27jloXVVuJTghk7ZHOpdO1MfONU/Mm2V6jPfnMRzw5mgWtuuMLeRs1QL9K5gm7dwFvacajUyEFB56r/W49iiD7m5wkH4KOeYFt9ZoDCLgeaEQlQ==
  indexer:RDS_PASSWORD:
    secure: v1:6OldikDHGPtFsshU:3tg0ETBuoOsjoCnrxja5zQnWyaGOSvtIsNEIjH2uu7tvuA==
  indexer:CHAIN_ID: "11155111"
  indexer:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic
