secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAHrK+9eIhmBLBN6ZFD95Zt5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJiII6Tq9vuswLTfCAgEQgDvyHa6T6MOS6fS5LOeXmlndVkK81At8L0sVFHS8pwDm2DS2RNagK/ZtEAsITGbkpmvh3d9xN5bDrmS9Uw==
config:
  aws:region: us-west-2
  indexer:BASE_STACK: organization/bootstrap/services-prod
  indexer:BOUNDLESS_ADDRESS: 0xfd152dadc5183870710fe54f939eae3ab9f0fe82
  indexer:CHAIN_ID: "8453"
  indexer:DOCKER_DIR: ../../
  indexer:DOCKER_TAG: latest
  indexer:GH_TOKEN_SECRET:
    secure: v1:ZOGVwhNMaKZIjMVi:ie7KmxAIw5IdgFdeDl4GvbwMq1xrZqRGzEVdtqsAfGXjFgfNc3oQs9t8kf2NhIPP/gJ+GEgVZSaQMW9z2Uv6v88Sptb/cOmanexVu5skHv3qcEh6pm3T+NaOu1EWGrxqSD8sgMUlsulbh6+TZA==
  indexer:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  indexer:RDS_PASSWORD:
    secure: v1:dYPYATp59XJzpu9S:iPZ7dZZ+VxIIqykU5iHZAgXNyBmDY5RT6sFzLkQPp/Z4VA==
  indexer:RUST_LOG_API: debug
  indexer:RUST_LOG_MONITOR: info,indexer_monitor=debug
  indexer:RUST_LOG_INDEXER: info,boundless_indexer=debug
  indexer:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic-launch
  indexer:START_BLOCK: "35060420"
  indexer:ETH_RPC_URL:
    secure: v1:czlCLunFJFxNK5Kt:6I6pDBuQfNFCQ5Of68Z3Vmdiw9tpMdp1bFLPgOKcV1e8n8vRsXyOodPLfAwERKn0gV4erCJs954Nn2FjwNIFEVIT5JkPAFXabRY6SaZshgYqcepfKQSpOkrpTTbaTDdkH/+ov4QaqkXS3jZVlJvFmA==
  indexer:ORDER_STREAM_URL: https://base-mainnet.boundless.network
  indexer:ORDER_STREAM_API_KEY:
    secure: v1:RiQ9dH2J6lynxHnr:CNEbbDvPjX/8bkttAQE8/JyLeVbNvG7wCTyCUoHV
  indexer:LOGS_ETH_RPC_URL:
    secure: v1:8fWY91B8U6ML9g8R:tYwI5eLET2ZoRSfpqjAbCNl0GLkNT5Z85VywuEN0kb6UiQSWf6qXPnebasmODFFcI9CKMD8Nr5gfcJh09JiQhxzaFouGPMu7WGfo
  indexer:BENTO_API_URL:
    secure: v1:xD9x2Do54QsoZ8z9:E+vSeXm3g3Oy5YrannT284/+x3P0d9V35x89Skdti41ML1KocppwWyvDjlYotZXhggRePlFJ0bytRQTpNj20/wXJOo4tsFgL/RHpp4GzTHB4PThXuyM=
  indexer:BENTO_API_KEY:
    secure: v1:qJcWpUCoJ+WigTSB:zuB+u/ZWBkrwqnRZwI8UbjqXl5JM/bqCOIdn6wpeepWgbmrnAzGUeN4vqxwJDiYdtkrSMkL1PFBcjhk=
  indexer:PROXY_SECRET:
    secure: v1:lJlgu7dJjEdBpg+J:49guE+TSvKTHVlf/LXakKarxpItokDS83AbT1XKJ2nAme8PrEX0Gcg==
  indexer:ALLOWED_IP_ADDRESSES:
    secure: v1:A5Mdx/awHcbvku4U:xbYCVcJVzRrHibChfMILD8Zeb+G9g6qNiTZMoZkR/OU=
